version: "3.9"
services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - 3306:3306
  keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    environment:
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloakdb
      - DB_USER=keycloakuser
      - DB_PASSWORD=keycloakpw
    ports:
      - 8080:8080
    depends_on:
      - mysql
#  jenkins:
#    image: jenkins/jenkins:lts
#    ports:
#      - 8181:8080
#      - 50000:50000
#    volumes:
#      - ./jenkins_home:/var/jenkins_home
